version: '3.9'

networks:
  # network for BE<->FE communication
  hdlt_net_be_fe:
    name: hdlt_net_be_fe

# volumes:
#   hdlt-fe-static:
#     name: hdlt-fe-static

services:
  hdlt-fe-nginx:
    image: hdlt-fe-dev
    container_name: hdlt-fe
    build:
      context: .
      dockerfile: .docker/Dockerfile
      target: build
      args: 
        APP_NAME: hdlt-fe
        APP_ROOT: /opt/hdlt-fe
        DOCKER_INTERNAL_PORT: 3000
        BASE_URL: ${BASE_URL}
    restart: unless-stopped
    environment:
      - APP_ENVIRONMENT=development
      - APP_NAME=hdlt-fe
      - DOCKER_INTERNAL_PORT_DEV=3000
      - BASE_URL
    volumes: 
      - ./:/opt/hdlt-fe
      - /opt/hdlt-fe/node_modules
    # cpus: 0.33
    # dns:
    #   - 10.4.5.130
    #   - 1.1.1.2
    #   - 1.0.0.2
    # mem_reservation: 128m
    ports:
      - 3000:3000
    networks:
      - hdlt_net_be_fe
    # labels:
    #   - "traefik.http.routers.${APP_NAME}.rule=Host(${APP_URLS_TRAEFIK})"
    #   - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=${DOCKER_INTERNAL_PORT}"
    #   - "traefik.docker.network=${DOCKER_NETWORK_NAME}"
    command: npm run dev

