name: deployment

on:
  workflow_dispatch:
    # inputs:
    #   environment:
    #         description: 'Environment'
    #         required: true
    #         type: choice
    #         options:
    #           - 'UAT'
    #           - 'PROD'
    #         default: 'UAT'

jobs:

  build:
    runs-on: ${{ vars.RUNNER_LABEL }}
    steps:
    - uses: actions/checkout@v3
    - name: Build static files for nginx container.
      env:
        BASE_URL: ${{ vars.BASE_URL }}
      run: make build

  deploy:
    runs-on: ${{ vars.RUNNER_LABEL }}
    needs: [ build ]
    steps:
    - name: Deploy Docker Container, recreate Container with fresh image.
      run: make run

