name: deployment

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:

  build:
    runs-on: [ citadel ]
    steps:
    - uses: actions/checkout@v4
    - name: Build
      env:
        APP_NAME: ${{ secrets.APP_NAME }}
        BASE_URL: ${{ secrets.BASE_URL }}
        NODE_ENV: production
        DOCKER_NETWORK_NAME: ${{ secrets.DOCKER_NETWORK_NAME }}
        APP_URLS_TRAEFIK: ${{ secrets.APP_URLS_TRAEFIK }}
        DOCKER_INTERNAL_PORT: ${{ secrets.DOCKER_INTERNAL_PORT }}
        DOCKER_EXTERNAL_PORT: ${{ secrets.DOCKER_EXTERNAL_PORT }}
        LOKI_URL: ${{ secrets.LOKI_URL }}
        LOKI_LABELS: ${{ secrets.LOKI_LABELS }}
      run: make build

  deploy:
    runs-on: [ citadel ]
    needs: [ build ]
    steps:
    - name: Deploy
      env:
        APP_NAME: ${{ secrets.APP_NAME }}
        BASE_URL: ${{ secrets.BASE_URL }}
        NODE_ENV: production
        DOCKER_NETWORK_NAME: ${{ secrets.DOCKER_NETWORK_NAME }}
        APP_URLS_TRAEFIK: ${{ secrets.APP_URLS_TRAEFIK }}
        DOCKER_INTERNAL_PORT: ${{ secrets.DOCKER_INTERNAL_PORT }}
        DOCKER_EXTERNAL_PORT: ${{ secrets.DOCKER_EXTERNAL_PORT }}
        LOKI_URL: ${{ secrets.LOKI_URL }}
        LOKI_LABELS: ${{ secrets.LOKI_LABELS }}
      run: make run

  clear_cf_cache:
    runs-on: [ citadel ]
    needs: [ deploy ]
    steps:
    - name: Clear Cloudflare cache
      run: |
       curl -X POST "${{ secrets.CF_CACHE_CLEAR_URL }}" \
        -H "Authorization: Bearer ${{ secrets.CF_CACHE_CLEAR_API_KEY }}" \
        -H "Content-Type:application/json" \
        -d '{"purge_everything": true}'